services:
  aistor:
    image: quay.io/minio/aistor/minio:latest
    container_name: aistor
    restart: unless-stopped

    ports:
      - "9000:9000"
      - "9001:9001"

    volumes:
      - ./data:/mnt/data
      - ./certs:/etc/minio/certs
      - ./minio.license:/minio.license

    environment:
      MINIO_ROOT_USER: ${AI_STORAGE_ACCESS_KEY}
      MINIO_ROOT_PASSWORD: ${AI_STORAGE_SECRET_KEY}

    command:
      - minio
      - server
      - /mnt/data
      - --license
      - /minio.license
      - --console-address
      - ":9001"

  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE}
    volumes:
      - mongodb_data:/data/db


  redis:
    image: redis
    ports:
      - "6379:6379"
    command: redis-server --requirepass ${REDIS_PASSWORD}
    volumes:
      - redis_data:/data

volumes:
  mongodb_data:
  redis_data:
